/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DownArrow: typeof import('./../components/icon/down-arrow.vue')['default']
    FigureItem: typeof import('./../components/figure-item.vue')['default']
    MouseMove: typeof import('./../components/icon/mouse-move.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
